### ISSUE TITLE
NoSuchMethodError: createInfoJPanel or createInfoPanel

### ISSUE THREAD

**Issue by jpsacha** [ij-plugins/ijp-toolkit#17]
When a plugin like the Seeded Region Growing Tool plugin is run from within ImageJ (outside of development project)
```
java.lang.NoSuchMethodError: net.sf.ij_plugins.util.IJPUtils.createInfoJPanel(Ljava/lang/String;Ljava/lang/String;)Ljavax/swing/JPanel;
	at net.sf.ij_plugins.grow.RegionGrowingView.initComponents(RegionGrowingView.java:71)
	at net.sf.ij_plugins.grow.RegionGrowingView.<init>(RegionGrowingView.java:58)
	at net.sf.ij_plugins.grow.RegionGrowingToolPlugIn.run(RegionGrowingToolPlugIn.java:57)
	at ij.IJ.runUserPlugIn(IJ.java:233)
	at ij.IJ.runPlugIn(IJ.java:196)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Likely naming conflict with other module like `ijp-color` or `debayer`

**Comment by jpsacha** [comment]
The cause of the problem is in ij-plugins/ijp-DeBayer2SX#8 - it was fixed
